### ISSUE TITLE
Text color selection issue

### ISSUE THREAD

**Issue by the43rddev** [alexpvpmindustry/alexwebpublic#2]
normally selecting white texts and the color is ok.
![image](https://github.com/alexpvpmindustry/alexwebpublic/assets/72349123/8769da86-bbe5-4e07-a696-36440bcfd33b)
but when selecting dark text, it is unreadable
![image](https://github.com/alexpvpmindustry/alexwebpublic/assets/72349123/600ad704-e3f9-436e-87cd-9101eb0e4d70)

**Comment by alexpvpmindustry** [comment]
right... maybe we need to change the highlight color... somewhere in the css

**Comment by alexpvpmindustry** [comment]
wait a sec... this is not the main repo, its migrated to https://github.com/DogeMultiverse/DogeMultiverseWebsite

**Comment by the43rddev** [comment]
forgor
